- lib/request-handler.js
> remove dev.knative headers condition

- lib/health-check.js
This commit extracts the code shared by the `readinessURL`, and
`livenessURL` to function to avoid some code duplication.
> src: add callProtect function

- README.md
- index.js
This command adds the curl example that is currently in index.js to the
readme.
> src,doc: Add url example to README.md

- index.js
- lib/context.js
- test/test.js
Provides the fastify server's structured logger to functions via the context.
> feat: provide structured logger to functions in context

- lib/event-handler.js
- test/test.js
> Improved error reporting

- package.json
> src: fix minor indentation

- .eslintrc
- index.js
- lib/ce-constants.js
- lib/event-handler.js
- package-lock.json
- package.json
- test/test.js
This will need to be modified once the next version of the SDK has been
released to 2.0.0.
> lib: change to cloudevents-sdk 2.0.1

- .github/workflows/release-please.yaml
- package-lock.json
- package.json
I'm liking this action for managing changelogs and releases.
This adds the release-please action for creating release PRs and landing a release when the PR lands. This removes the `release` task in package.json.
> chore(actions): add release-please on push to 'master'

- lib/event-handler.js
- package-lock.json
- package.json
- test/test.js
> deps: update to CloudEvents 4.0.0 and some linting

- .github/workflows/ci.yml
- .github/workflows/release-please.yaml
> chore: change ci branch names for releases

- lib/health-check.js
> chore: set log level to warn for health checks

- test/test.js
> chore: add a test for events with text/plain data

- test/test-context.js
- test/test.js
Signed-off-by: Matej Vasek <mvasek@redhat.com>
> src: add reject callbacks

- lib/invoker.js
- test/fixtures/cloud-event/index.js
- test/fixtures/cloud-event/with-response.js
- test/test.js
The result of discussion over here: https://github.com/boson-project/func/pull/356
> Instead of its data, pass the CloudEvent to the handler

- .github/workflows/ci.yml
- .gitignore
- README.md
- package-lock.json
- package.json
Also does a few other things
- add Node.js v18 to test matrix
- remove some stray leftover config from standardx
- adds codecov badge to readme
/kind chore
> chore(coverage): upload coverage stats to codecov.io

- .github/workflows/release-please.yaml
Adds headings for non-standard release-please changelog types, and bumps the release-please dependency to the latest major version.
/kind chore
> chore(release-please): specify changelog headings

- README.md
Adds information about function signatures using TypeScript types and interfaces. Some other minor cleanup.
/kind documentation
Preview link: https://github.com/boson-project/faas-js-runtime/blob/f1416ced313ac49f8022d33c9117c2103d91ea4d/README.md
> documentation(README.md): update with interfaces and types

- .github/workflows/release-please.yaml
Releases are broken until this lands.
/kind chore
> feat(release-please): bump node version

- package-lock.json
- package.json
Fixes issues with typescript types in cloudevent function projects.
/kind fix
> fix(cloudevents): bump to latest release

- package-lock.json
- package.json
- sbom.json
This commit adds a dev dependency on @cyclonedx/cyclonedx-npm to generate an `sbom.json` file after each run of `npm install`. If the dependencies have changed, the `sbom.json` file will be updated. Finally, `sbom.json` is added as a file to the distributed package.
> feat: adds sbom.json as install artifact

- .github/workflows/release-please.yaml
- .github/workflows/release.yaml
This makes sure that the on:release:created action gets triggered from another workflow
> chore: update the token that release-please runs with.

- lib/invoker.js
- test/fixtures/response-structured/index.js
- test/test.js
> Do not overwrite headers of StructuredReturn

- index.d.ts
- index.js
- lib/types.d.ts
- lib/utils.js
- package.json
- test/test-lifecycle.js
- tsconfig.json
Allow for `init` and `shutdown` functions to return promises.
> Allow for async init and shutdown functions

- package.json
This PR normalizes repository url as the `npm pkg fix` command suggests.
> Normalizing repository url
