- test/test.js
Currently, the test are failing with the following error:
```console
$ rm -rf test/fixtures/simple-http/node_modules/
$ npm t
> @redhat/faas-js-runtime@0.0.2 test /work/faas-js-runtime
> nyc tape test/*.js | tap-spec
Loads a user function with dependencies
internal/modules/cjs/loader.js:626
throw err;
^
Error: Cannot find module 'is-number'
Require stack:
/work/faas-js-runtime/test/fixtures/simple-http/index.js
/work/faas-js-runtime/test/test.js
```
This commit adds the fixture director so that the package.json files in
the fixtures are found.
> test: fix path to test fixtures

- lib/request-handler.js
Currently, the field func is initialized but it always gets overritten
as far as I can tell. This commit removes the initalization.
> src: don't initialize func

- index.js
- test/test.js
This commit adds an options paraemeter to the start function. Currently
this only holds one field which is boolean named log. This allows
logging to be toggled.
This commit also updates the test to set log to false so the output is
less noisy.
> src: add options parameter to start

- test/test.js
This commit adds readdirSync to the existing object destruction of the
fs module instead of requiring the fs module twice.
> test: don't require fs module twice

- hack/run.js
This commit adds a require function call for the example in the fixtures
directory. This require was previously done by the framework but that
was changed which broke this example.
> src: fix hack example

- lib/ce-constants.js
- lib/event-handler.js
- test/test.js
This commit adds constants for the HTTP headers that are used for cloud
events.
> src: add constants for cloudevent headers

- lib/context.js
- package.json
- test/fixtures/cloud-event/with-response.js
- test/test.js
This commit adds a method to the Context class that is intended to be
used by services that which to respond with a cloud event message. The
function will decorate a Response setting headers using functions
saving users from having to find and set the correct headers.
> src: add ce response decorator

- lib/event-handler.js
- package-lock.json
- test/test.js
The cloudevents sdk has some inconsistencies with how it exposed the
unmarshalling. Version 0.3 and earlier had an async API, while 1.0
(smartly) changed that. As a result, the impl in this file was pretty
ugly. By using the receivers directly, we can avoid that and clean up
this code.
These changes are based on: https://github.com/cloudevents/sdk-javascript/pull/120
Once those changes land in a released version of the cloudevents sdk
this file can be even simpler as the sdk will handle most of this work.
As an aside - dropped support for 0.2. Normally I wouldn't be so casual about
dropping support, but upstream sdk has no 0.2 support in the next release
and cloud events spec says only the two most recent versions are required
to be supported.
> chore: clean up event unmarshalling, remove async API calls

- lib/ce-constants.js
- lib/event-handler.js
- package-lock.json
- package.json
- test/test.js
This commit updates the cloudevent-sdk to use the newly named cloudevents
module at version 3.0.1.
> lib(deps): update to cloudevents 3.0.x

- index.js
- lib/ce-constants.js
- lib/event-handler.js
- package-lock.json
- package.json
- test/fixtures/async/index.js
- test/fixtures/cloud-event/index.js
- test/fixtures/json-input/index.js
- test/test.js
This change bumps the runtime cloudevents dependency to 3.1.0, and the runtime fastify dependency to 3.2.0.
This also fixes some tests that began failing after a the earlier bump to cloudevents 3.0.0
> deps: bump to cloudevents 3.1.0 and fastify 3.2.0

- index.js
- lib/event-handler.js
- lib/request-handler.js
- package-lock.json
- package.json
Changes in 3.2.1 to fastify resulted in a broken framework. The fastify
module added a `context` property to the request object, which we had
been decorating with a property by the same name. This commit bumps to
the latest 3.3.0 of fastify, and changes the property that we decorate
the request object with to `fcontext`. These changes are entirely
internal and do not affect the user function.
> deps: bump to fastify 3.3.0

- package-lock.json
- package.json
The major version bump is because support for Node.js 8 has been dropped. This shouldn't affect us - especially considering that this dependency is only used for releases and we're not supporting Node.js 8.
```
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ dot-prop                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ standard-version [dev]                                       │ …
```
> deps: bump standard-version to 9.0.0

- README.md
- package-lock.json
- package.json
This commit removes the `@redhat` prefix from the module name, since the prefix should be reserved for productized modules.
Note that this is a BREAKING CHANGE
> feat: change module name to faas-js-runtime

- lib/context.js
- test/test.js
This commit removes the openwhisk variables that were added to the context object early in this project's life, when we were not sure if we would support running in openwhisk.
> fix: remove openwhisk varaiables from context

- .github/workflows/release-please.yaml
The ID is used later in the action to determine if a release was actually created.
Since it wasn't set, an automated release did not occur for 0.3.0. This fixes that.
> chore(actions): add id to release-please action

- lib/invoker.js
- test/fixtures/cloud-event/index.js
- test/fixtures/cloud-event/with-response.js
- test/test.js
If a CloudEvent is the incoming HTTP request, and if the data attribute
has been set, provide it as the second parameter to the function invocation.
This makes the module work a bit more like funqy, but we still expose
a context object.
> feat: provide cloudevent data if it exists as first parameter to function

- lib/invoker.js
- test/test.js
This commit ensures that a CloudEvent function is correctly invoked when an event with no data is received.
/cc @slinkydeveloper 
Fixes: https://github.com/boson-project/faas-js-runtime/issues/66
> fix: handle cloudevents that have no data

- lib/context.js
- lib/invoker.js
- lib/request-handler.js
- package-lock.json
- package.json
- test/fixtures/query-params/index.js
- test/test-context.js
- test/test.js
We already **kind of** handled them, but these changes make it more intuitive
for the user. For example, the function author can respond with `new CloudEvent(...)`
or `HTTP.binary(event)` and the framework should handle the response correctly.
This partially fixes https://github.com/boson-project/functions/issues/15
> feat: handle CloudEvent and Message responses from function invocation

- lib/event-handler.js
- lib/invoker.js
- test/fixtures/cloud-event/index.js
- test/fixtures/cloud-event/with-response.js
- test/test.js
To make it possible for functions to easily act as both HTTP and CloudEvent
handler it's better to have any potential data as the second parameter.
This change also makes use of a new bit of the cloudevents API to receive an
incoming event, eliminating a transitive dependency on axios.
Fixes: https://github.com/boson-project/faas-js-runtime/issues/62
Fixes: https://github.com/boson-project/faas/issues/194 (when updated in thetemplate)
BREAKING CHANGE
> fix: reverse the parameter order when invoking

- bin/cli.js
Fixes: https://github.com/boson-project/faas-js-runtime/issues/73
Now, instead of this:
```
> npx faas-js-runtime ./index.js
(node:3724996) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
at Server.setupListenHandle [as _listen2] (net.js:1317:16)
at listenInCluster (net.js:1365:12)
at doListen (net.js:1502:7)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3724996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use …
```
> fix: better error handling when network address is already in use

- README.md
- index.js
- test/test-context.js
- test/test.js
This PR adds support for configurable log levels. 
It's neat that pino is used as the logger, but currently it can only be toggled on/off. This PR will support passing a `logLevel` in the options passed to the runtime. 
This PR defaults the log level to `info` which provides the same behaviour as the previous `true` value, so it shouldn't affect people who are OK with the existing defaults when they update.
> Support configurable log levels

- package.json
- test/fixtures/http-get/.npmrc
- test/fixtures/http-post/index.js
- test/fixtures/no-content/index.js
- test/test.js
* added .npmrc to test/fixtures/http-get/ directory
to avoid package-lock.json changes during the tests
and showing git diffs
* linting config as suggested by Node.js Ref Architecture
https://github.com/nodeshift/nodejs-reference-architecture/blob/main/docs/development/code-consistency.md#guidance
* minor lint fixes in tests
> chore: minor updates

- .eslintrc
- bin/cli.js
- index.d.ts
- index.js
- lib/context.d.ts
- lib/event-handler.js
- package-lock.json
- package.json
- test/test-context.js
- test/test.js
- test/types/context.test-d.ts
- test/types/index.test-d.ts
- tsconfig.json
This commit adds type definitions for the following:
* `Invokable`: The user provided function
* `Context`: The invocation context
* `CloudEventResponse`: Convenience class for constructing events
* `Logger`: The logging interface
* `LogLevel`: Logging enumeration
* `start`: A function to start the invoker
* `InvokerOptions`: Options for `start`
The definitions are statically tested with `tsd`.
These type definitions are not actually used by the JS files. This does not
convert the module to TypeScript; it just adds these type definitions to our
exports. This will allow us to create TypeScript function templates without
a full conversion of this code base to TypeScript. Ultimately, I think it's
probably best to make the change.
This change also bumps to `cloudevents@4.0.2` which does have …
> feat: add TypeScript type definitions

- README.md
- bin/cli.js
- index.js
- test/test-context.js
- test/test.js
This allows TypeScript clients to import `start` like so.
```TypeScript
import { start } from 'faas-js-runtime';
start(fn);
```
Otherwise, there was a problem with a default import of `start` in index.js
but a `const` type declaration of `start` in index.d.ts. This change fixes that
> fix: change index.js to not have a default export

- bin/cli.js
This allows a user to specify the FUNCTION_LOG_LEVEL and LISTEN_PORT as environment variables for the cli to pick up.
This makes it a little more consistent with how the Buildpack uses the runtime
> fix(cli): Adds the ability to pass logLevel and port from the cli.

- index.d.ts
TypeScript type updates overlooked in recent change to invokable function signature.
> fix: fix Invokable type signature

- test/types/index.test-d.ts
> fix: use cloudevent as second param in test fn

- bin/cli.js
- index.d.ts
- index.js
- package-lock.json
- package.json
- test/fixtures/funcyaml/func.yaml
- test/fixtures/funcyaml/index.js
- test/test.js
- test/types/index.test-d.ts
This commit introduces an `options.config` parameter to `start()` which
may point to a directory or a `func.yaml` file. When the server starts,
this config file will be read, if it exists, to determine the expected
log level.
Note that this determines the __defaults__ upon server start up. These
may be overridden via the options parameter as usual. E.g. calling
`start(func, { logLevel: 'trace' })` will set the log level to `trace`
no matter what's in `func.yaml`.
See: https://github.com/knative-sandbox/kn-plugin-func/pull/462
> feat: add limited support for func.yaml via logLevel

- lib/invoker.js
- test/test-scope.js
Prevents functions from having access to the global scope during
function invocation. Currently the scope is a frozen, empty object.
Fixes: https://github.com/boson-project/faas-js-runtime/issues/117
> fix: add an explicit scope to function invocation

- index.js
- package-lock.json
- package.json
Also adds support for IPv6 in the `listen()` call.
/kind chore
> chore(deps): bump fastify to 4.9.x

- .github/workflows/ci.yml
- .gitignore
- lib/function-loader.js
- test/fixtures/esm-module-type-up-dir/build/index.js
- test/fixtures/esm-module-type-up-dir/package.json
- test/test-function-loading.js
This resolves issues where function source may be in a subdirectory, for example `./build` in a TypeScript project.
Fixes: https://github.com/boson-project/faas-js-runtime/issues/143
> fix: modify module loader to look in parent directories

- package-lock.json
```
npm audit
qs  6.9.0 - 6.9.6
Severity: high
qs vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-hrpp-h998-j3pp
fix available via `npm audit fix`
node_modules/formidable/node_modules/qs
formidable  2.0.0-canary.20200129.2 - 2.0.1
Depends on vulnerable versions of qs
node_modules/formidable
2 high severity vulnerabilities
To address all issues, run:
npm audit fix
```
> chore(deps): update transitive dependencies

- bin/cli.js
Ensure quick shutdown when browsers are holding open a connection.
Fixes: https://github.com/nodeshift/faas-js-runtime/issues/120
> fix: add `process.exit(0)` in `ON_DEATH` hook

- README.md
- package.json
Updates the README.md badges to point to the nodeshift orgs on GitHub and Codecov. Updates the package.json references to boson-project (although these will redirect anyway).
> chore: update README.md and package.json for nodeshift

- .github/workflows/ci.yml
- README.md
This also adds Node 18 to the lts section of the ci workflow as well as removing the 'current' section.
fixes #124
> chore: Add the node version support to the readme.

- .github/workflows/release-please.yaml
After moving to nodeshift, the existing token was deleted from npm and a new token was created with more limited publish permissions - only able to publish this repo. The name was changed to FAAS_JS_RUNTIME_PUBLISH.
/cc @lholmquist
> chore: update the publish token name for npm

- .github/workflows/ci.yml
- .github/workflows/release-please.yaml
The current actions in use (v2 and v1 respectively) use Node.js 12 and are now deprecated. See: https://github.com/nodeshift/faas-js-runtime/pull/193#issuecomment-1468528740
> chore: bump checkout and setup-node actions to v3

- .github/workflows/release-please.yaml
- .github/workflows/release.yaml
This pulls the actual publication of the module into its own workflow, which is run when a release is created. It also adds sigstore provenance to the publication so that the release is signed by sigstore and logged in a public transparency ledger.
See: https://docs.npmjs.com/generating-provenance-statements
See: https://www.sigstore.dev/
> chore: move publish to its own workflow and add sigstore provenance

- package.json
- sbom.json
By having the sbom generated during the `postinstall` step, we have inadvertently made the package impossible to install as a dependency. This is because when installing this as a dependency in a project, `npm install` is run under the hood. Subsequently, `npm run postinstall` happens, but the published package does not contain a package-lock.json file and the sbom generation fails, therefore failing the installation of the module altogether.
This commit modifies the npm scripts so that the sbom generation happens only when publishing, and the publish will fail if there are any modified files in the repo, i.e. if the sbom was updated. This means it is incumbent on maintainers of this package to keep the sbom up to date by periodically running `npm run sbom` when modifying dependencies. If …
> chore: change sbom generation to happen on `prepublishOnly`

- package-lock.json
- package.json
- sbom.json
@lance i "borrowed" this from your release-please issue :) 
The Context:
When the release PR is merged, this includes changes to the package-lock.json file which in turn results in a modification of the SBOM, which means that when the release is published, the SBOM is out of date.
A tangible example:
clone this repository: https://github.com/nodeshift/faas-js-runtime change into the repo directory and run git checkout v2.2.1 (the most recent release tag) run npm run sbom which generates an SBOM based on the current package-lock.json file run git diff to see what should have been included in the release SBOM
> fix: temporarily removes the prePublish step allowing us to publish a new version and for users to use this module.

- .github/workflows/release-please.yaml
This commit adds SBOM generation during the release-please PR creation action. If no release was created, it checks out the known release-please PR branch, runs `npm run sbom` to update the package SBOM on the PR branch, and commits the result.
/kind chore
/cc @lholmquist
> chore: add sbom generation to release-please action

- README.md
- index.js
- lib/invocation-handler.js
- lib/invoker.js
- lib/types.d.ts
- test/test.js
**Reasoning**
- At the moment, no support for OPTIONS request is implemented. This is the preflight request for CORS checks, thus API calls to a serverless function from a web browser is failing.
**Changes**
- Enable preflight response **[OPTIONS]** with generic cors allow.
- Export a function "cors" where you can specify the allowed origins.
> Enable OPTIONS preflight and a method to enable cros origins

- lib/invoker.js
* Fixed dereference of undefined on fnReturn when user function does not return/returns undefined.
* Fixed error in logging.
> Fix dereference of undefined
